Localize jp
v-community/v_by_example pull request #164
Opened 2020-03-08 09:32 UTC by hachi8833

Retry of  #154

2020-03-08 10:02 UTC, Delta456 requested changes
Please translate that section

2020-03-08 10:02 UTC, Delta456 commented on jp/examples/section_1/comment.md
> +# Comments
Please translate this section

2020-03-09 05:20 UTC, Delta456 commented
Also see #154

2020-03-09 05:23 UTC, hachi8833 commented on jp/examples/section_1/comment.md
> +# Comments
Translated

2020-03-09 08:13 UTC, Delta456 requested changes

2020-03-09 08:13 UTC, Delta456 commented on jp/examples/section_1/hello_world.md
> +example_title: hello world
Translate this as well

2020-03-09 16:24 UTC, merged